

server:
  port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ele?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: ""
        driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.shellming.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug