

server:
  port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ele?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: ""
        driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.shellming.elservice.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

# pageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# JWT
jwt:
  # 发行者
  name: Hilox
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: SGlsb3g=
  #jwt中过期时间设置(分)
  jwtExpires: 120

#Redis
redis:
    #    默认配置
  database: 0
  host: 127.0.0.1
  port: 6379
  password: ""
  timeout: 2000
  lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    #    自定义配置
  local:
      host: 127.0.0.1
      port: 6379
      password: ""
